apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  labels:
    app: grpc-server
spec:
  type: LoadBalancer
  ports:
    - port: 4040
      protocol: TCP
      targetPort: 4040
  selector:
    app: grpc-server
