apiVersion: v1
kind: Service
metadata:
  name: grpc-client
  labels:
    app: grpc-client
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: grpc-client
